# Generated by Django 2.2.3 on 2019-07-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book_id',
            new_name='book',
        ),
    ]
